import type { Metadata } from "next";
import "./globals.css";
import CalendlyInit from "./calendly-init";

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by Landright",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CalendlyInit />
        {children}
      </body>
    </html>
  );
}
